# We learned how to store variables and use them in our code later. I made an interactive part for my project at the end.
# This is the first part
print("Definitely not a Phishing Scam")
print()
yourName = input("Your Name")
print("Thanks for logging in")
print(yourName)
cardNumber = input("What is your credit card number?")
print("Thanks, I definitely wont put")
print(cardNumber)
print("into Amazon and order anything weird")
print()
print("Promise")
maidenName = input("What is your Mother's maiden name? ")
print()
print("That's cool, I just wanted to know that")
print(maidenName)
print("was your Mum's maiden name. Not because the bank requested it or anything, honest.")
# This is the project for day 2
print("Getting to know you!")
print()
myName = input("What is your name? ")
print("Nice to meet you" + myName)
myFood = input("What is your favorite food? ")
print("I like" + myFood + "too!")
myMusic = input("What is your favorite music? ")
print("I like" + myMusic + "too")
myLocation = input("Where do you live? ")
print(myLocation + "is a nice place to live")
